name: Generate Snake

# Triggers:
on:
  schedule:
    - cron: "0 * * * *"   # runs hourly automatically
  workflow_dispatch:       # allows manual run anytime

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate the snake SVG
      - uses: Platane/snk@v3
        with:
          github_user_name: frankbahirwa

      # Step 2: Publish the SVG to the 'output' branch
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
